/**
 * Sightseeing / photo / food / nature stops within ~20 min of the route.
 * Curated by a research pass across camper forums, TripAdvisor & Instagram.
 * A togglable "Sights" layer on the trip map — decide what to see as you go.
 */
export type PoiType =
  | "viewpoint"
  | "lake"
  | "castle"
  | "restaurant"
  | "attraction"
  | "nature"
  | "town";

export interface Poi {
  name: string;
  type: PoiType;
  lat: number;
  lng: number;
  near: string;
  blurb: string;
  source: string;
  stopLength: "photo" | "short" | "half-day";
}

export const POI_DATA: Poi[] = [
  { name: "Cap Blanc-Nez & Dover Patrol Obelisk", type: "viewpoint", lat: 50.9235, lng: 1.7015, near: "Calais / Éperlecques", blurb: "Dramatic white chalk cliffs topped by a WWI Dover Patrol obelisk, with views across the Channel to Dover and dog-friendly clifftop paths.", source: "park4night / Tripadvisor top things to do", stopLength: "short" },
  { name: "Cap Gris-Nez lighthouse", type: "nature", lat: 50.8681, lng: 1.5826, near: "Calais (short detour off the A16)", blurb: "France's closest point to England: a windswept lighthouse headland with seal-spotting and quiet clifftop walks.", source: "park4night / camper forums", stopLength: "short" },
  { name: "Blockhaus d'Éperlecques", type: "attraction", lat: 50.8286, lng: 2.1837, near: "Éperlecques (Château du Gandspette overnight)", blurb: "Colossal WWII V2-rocket bunker set in wooded parkland, a memorable history half-day right beside the Gandspette campsite.", source: "Tripadvisor / Saint-Omer tourist office", stopLength: "half-day" },
  { name: "La Coupole (Helfaut-Wizernes)", type: "attraction", lat: 50.7047, lng: 2.2371, near: "Saint-Omer (short detour south of Éperlecques)", blurb: "Vast concrete dome hiding an underground V2 launch complex, now a well-rated history museum and planetarium for a wet-weather half-day.", source: "Tripadvisor / LeShuttle traveller guides", stopLength: "half-day" },
  { name: "Rozenhoedkaai, Bruges", type: "viewpoint", lat: 51.2076, lng: 3.2277, near: "Bruges", blurb: "The most photographed canal corner in Bruges, all stepped gables and reflections, and the start point for dog-friendly boat trips.", source: "Instagram-famous / Tripadvisor", stopLength: "photo" },
  { name: "Minnewater (Lake of Love) & Beguinage, Bruges", type: "lake", lat: 51.2003, lng: 3.2245, near: "Bruges", blurb: "Postcard 'Lake of Love' with swans and an arched bridge beside the tranquil walled Beguinage garden, an easy walk from the centre.", source: "Dog-friendly Bruges guides / Tripadvisor", stopLength: "short" },
  { name: "Damme", type: "town", lat: 51.2517, lng: 3.2831, near: "Bruges (6 km north-east)", blurb: "Storybook polder village reached by a poplar-lined canal from Bruges, with a windmill and a flat towpath ideal for a dog walk.", source: "Tripadvisor / cycling blogs", stopLength: "short" },
  { name: "Oudenaarde old town & Town Hall", type: "town", lat: 50.8497, lng: 3.6009, near: "Flemish Ardennes", blurb: "Relaxed Flemish Ardennes town with a late-Gothic UNESCO town hall, Scheldt-side walks and brasseries serving local beers.", source: "VisitFlanders / Tripadvisor", stopLength: "short" },
  { name: "De Muur van Geraardsbergen", type: "viewpoint", lat: 50.7686, lng: 3.8817, near: "Flemish Ardennes (Geraardsbergen)", blurb: "Legendary cobbled Tour of Flanders climb topping out at a hilltop chapel with sweeping views, a rewarding leg-stretch with the dog.", source: "Tripadvisor / cycling spots", stopLength: "short" },
  { name: "European Museum Schengen", type: "attraction", lat: 49.4675, lng: 6.3667, near: "Luxembourg Moselle (Camping Bissen area)", blurb: "The riverside spot where borderless Europe was signed, with a small museum, three-borders monument and a Moselle promenade to wander.", source: "Tripadvisor / Visit Luxembourg", stopLength: "short" },
  { name: "Koeppchen chapel viewpoint, Wormeldange", type: "viewpoint", lat: 49.6103, lng: 6.4108, near: "Luxembourg Moselle (Wine Route)", blurb: "Little vineyard chapel above Wormeldange with one of the Moselle valley's finest panoramas over its terraced Riesling slopes.", source: "Visit Moselle / camper forums", stopLength: "photo" },
  { name: "JK Winery / Vinsmoselle stop, Ahn", type: "restaurant", lat: 49.6236, lng: 6.4262, near: "Luxembourg Moselle (Ahn, on the Wine Route)", blurb: "Camper-favourite vintner where you can park beside the vines, taste 'CamperWine' and soak up the Moselle valley view.", source: "park4night / camper forums", stopLength: "short" },
  { name: "Vianden Castle", type: "castle", lat: 49.9351, lng: 6.2045, near: "Camping Bissen, Luxembourg", blurb: "One of Europe's grandest Romanesque-Gothic hilltop castles, a classic half-day with a chairlift up the valley, twenty minutes from Bissen.", source: "Camping Bissen guide / Tripadvisor", stopLength: "half-day" },
  { name: "Esch-sur-Sûre", type: "town", lat: 49.9108, lng: 5.9364, near: "Camping Bissen, Luxembourg", blurb: "Cobbled riverside village wrapped in a bend of the Sûre beneath a 10th-century castle ruin, a short hop from the campsite.", source: "Camping Bissen guide / camper forums", stopLength: "short" },
  { name: "Schiessentümpel Waterfall (Mullerthal)", type: "nature", lat: 49.7784, lng: 6.2896, near: "Mullerthal / Echternach, Luxembourg", blurb: "Instagram-famous triple cascade under a little stone bridge in Luxembourg's 'Little Switzerland', a short dog-friendly walk from the car park.", source: "Tripadvisor / park4night", stopLength: "short" },
  { name: "Burg Landshut viewpoint, Bernkastel-Kues", type: "viewpoint", lat: 49.9126, lng: 7.0668, near: "Bernkastel-Kues, Mosel", blurb: "Ruined hill castle with a panoramic terrace over the Mosel's hairpin bend and vineyards, a five-minute walk from the car park.", source: "Komoot / motorhome guides", stopLength: "short" },
  { name: "Bernkastel-Kues old town (Marktplatz)", type: "town", lat: 49.9153, lng: 7.0725, near: "Bernkastel-Kues, Mosel", blurb: "The Mosel's prettiest wine town, a medieval market square of leaning half-timbered houses beside a riverside Stellplatz.", source: "mosel-inside / Campstar", stopLength: "short" },
  { name: "Mummelsee (Schwarzwaldhochstraße B500)", type: "lake", lat: 48.5953, lng: 8.2047, near: "Black Forest High Road / Baden-Baden", blurb: "Mystical glacial lake at 1,000 m on the scenic B500 high road, with a lakeside walk, pedalos and a camper-friendly car park.", source: "schwarzwaldportal / travel guides", stopLength: "short" },
  { name: "Allerheiligen Waterfalls & Abbey ruins, Oppenau", type: "nature", lat: 48.534, lng: 8.201, near: "Oppenau, northern Black Forest", blurb: "The Black Forest's highest natural falls tumbling beside atmospheric monastery ruins on a 4 km family loop from a free car park.", source: "Komoot / outdooractive", stopLength: "half-day" },
  { name: "Triberg Waterfalls", type: "attraction", lat: 48.1338, lng: 8.2308, near: "Triberg, central Black Forest", blurb: "Germany's famous 163 m cascade with a stroller-friendly trail, cuckoo-clock shops and a nearby camper aire.", source: "Tripadvisor / park4night", stopLength: "half-day" },
  { name: "Lake Titisee (Strandbad)", type: "lake", lat: 47.9016, lng: 8.154, near: "Titisee-Neustadt, southern Black Forest", blurb: "Clear-water swimming lake with a grassy lido, pedalos and a dog-friendly south bank, a classic family day out.", source: "Tripadvisor / hochschwarzwald.de", stopLength: "half-day" },
  { name: "Freiburg im Breisgau old town", type: "town", lat: 47.9955, lng: 7.8522, near: "Freiburg im Breisgau", blurb: "Genuinely medieval old town with a soaring Gothic minster, trickling Bächle water channels and a funicular up the Schlossberg for views.", source: "Tripadvisor / Expedia", stopLength: "half-day" },
  { name: "Eguisheim, Alsace", type: "town", lat: 48.0442, lng: 7.3075, near: "Colmar / Alsace fringe", blurb: "Fairytale concentric medieval streets of flower-decked half-timbered houses, one of France's most photogenic villages.", source: "Tripadvisor / Instagram", stopLength: "short" },
  { name: "Strasbourg – Petite France & Barrage Vauban", type: "attraction", lat: 48.5806, lng: 7.7407, near: "Strasbourg, Alsace", blurb: "UNESCO canal quarter of half-timbered tanners' houses, best photographed from the Barrage Vauban terrace.", source: "Tripadvisor / city guides", stopLength: "half-day" },
  { name: "Wildberg Old Town & Castle Ruin", type: "castle", lat: 48.6218, lng: 8.7437, near: "Camping Carpe Diem, Wildberg", blurb: "The overnight stop's own draw: a 12th-century castle spur above the Nagold with a half-timbered old town, minutes from the pitch.", source: "Tripadvisor / black-forest-travel.com", stopLength: "short" },
  { name: "Baumwipfelpfad Schwarzwald (Treetop Walk)", type: "attraction", lat: 48.7511, lng: 8.5468, near: "Bad Wildbad (approx 30 min from Wildberg)", blurb: "Barrier-free treetop walkway ending in a panorama tower with a tunnel slide back down, an ideal dog-friendly family half-day.", source: "Tripadvisor / blackforest-highlights.com", stopLength: "half-day" },
  { name: "Schloss Neuschwanstein", type: "castle", lat: 47.5576, lng: 10.7498, near: "Füssen (Fernpass approach to Tirol)", blurb: "The fairytale castle that inspired Disney, a bucket-list walk-up right on the Fernpass corridor into Tirol.", source: "Tripadvisor / Instagram", stopLength: "half-day" },
  { name: "Marienbrücke Viewpoint", type: "viewpoint", lat: 47.5581, lng: 10.7462, near: "Füssen / Neuschwanstein", blurb: "Footbridge over the Pöllat gorge framing Neuschwanstein head-on, a short uphill walk for the postcard shot.", source: "Instagram-famous / Tripadvisor", stopLength: "photo" },
  { name: "Eibsee", type: "lake", lat: 47.4574, lng: 10.98, near: "Garmisch-Partenkirchen", blurb: "Astonishing turquoise glacial lake below the Zugspitze with a flat lakeside loop and swimming bays, a favourite hot-day swim.", source: "park4night / Instagram", stopLength: "half-day" },
  { name: "Plansee", type: "lake", lat: 47.4888, lng: 10.8546, near: "Reutte, Tirol (Fernpass route)", blurb: "Panorama over Tirol's second-largest lake, a turquoise fjord ringed by Alps with a free bathing spot for a swim stop.", source: "park4night / tyrol.com", stopLength: "short" },
  { name: "Burgenwelt Ehrenberg & Highline179", type: "attraction", lat: 47.4811, lng: 10.7178, near: "Reutte, Tirol (Fernpass B179)", blurb: "Medieval castle ruins linked by a 406 m suspension footbridge, with flat camper parking and bridge views on the Fernpass.", source: "park4night / reutte.com", stopLength: "half-day" },
  { name: "Fernsteinsee", type: "lake", lat: 47.3547, lng: 10.8285, near: "Nassereith, Tirol (Fernpass summit)", blurb: "Jaw-dropping crystalline turquoise lake with a tiny castle islet, a classic roadside photo stop from the B179.", source: "Tripadvisor / Instagram", stopLength: "photo" },
  { name: "Swarovski Kristallwelten", type: "attraction", lat: 47.2967, lng: 11.6017, near: "Wattens (15 min east of Innsbruck)", blurb: "Surreal Giant's-head fountain and mirrored crystal art rooms with a big playground, a genuinely quirky kid-pleasing half-day.", source: "Tripadvisor top things to do", stopLength: "half-day" },
  { name: "Goldenes Dachl & Innsbruck Old Town", type: "town", lat: 47.2686, lng: 11.3933, near: "Innsbruck (near Wildermieming stop)", blurb: "The golden-tiled Goldenes Dachl and pastel arcaded lanes under the Nordkette peaks, compact and dog-friendly for a stroll and gelato.", source: "Tripadvisor / Instagram", stopLength: "short" },
  { name: "Hafelekar Viewpoint (Nordkette)", type: "viewpoint", lat: 47.3126, lng: 11.3849, near: "Innsbruck", blurb: "A dizzying 2,256 m panorama over Innsbruck and the Alps reached by the Nordkettenbahn, one of Austria's best city-mountain views.", source: "Tripadvisor / Instagram", stopLength: "half-day" },
  { name: "Stiftskeller Innsbruck (Biergarten)", type: "restaurant", lat: 47.2698, lng: 11.3922, near: "Innsbruck Old Town", blurb: "Large shaded beer garden in the old town serving Tirolean classics, relaxed and family- and dog-friendly for lunch.", source: "Tripadvisor / camper forums", stopLength: "short" },
  { name: "Hohensalzburg Fortress & Salzburg Altstadt", type: "castle", lat: 47.7947, lng: 13.0473, near: "Salzburg (A1 corridor)", blurb: "One of Europe's largest intact medieval fortresses crowning Mozart's baroque old town, a natural leg-stretch on the A1.", source: "Tripadvisor top things to do", stopLength: "half-day" },
  { name: "Augustiner Bräustübl Mülln", type: "restaurant", lat: 47.8072, lng: 13.0348, near: "Salzburg", blurb: "Austria's biggest beer garden, with chestnut-shaded benches and steins poured from wooden barrels, famously family- and dog-friendly.", source: "camper forums / Tripadvisor", stopLength: "short" },
  { name: "Mondsee lake & Basilica St Michael", type: "lake", lat: 47.8564, lng: 13.3494, near: "Mondsee (A1 corridor)", blurb: "Warm-water Salzkammergut lake off the A1 with a lido and dog beaches, plus the yellow 'Sound of Music' wedding church in town.", source: "campercontact / Tripadvisor", stopLength: "short" },
  { name: "Melk Abbey (Stift Melk)", type: "castle", lat: 48.2281, lng: 15.3339, near: "Melk", blurb: "Vast ochre baroque monastery on a rock above the Danube with a jaw-dropping library and terrace views, beside the Melk overnight stop.", source: "Tripadvisor / UNESCO", stopLength: "half-day" },
  { name: "Dürnstein blue church & castle ruins", type: "town", lat: 48.3956, lng: 15.5211, near: "Wachau / Melk", blurb: "The powder-blue baroque abbey tower over the Danube is the Wachau's signature shot, above a cobbled wine village and castle ruin.", source: "Instagram-famous / Tripadvisor", stopLength: "half-day" },
  { name: "Ruine Aggstein", type: "viewpoint", lat: 48.3103, lng: 15.4272, near: "Wachau / Melk", blurb: "Dramatic clifftop castle ruin 300 m above the Danube with one of the finest views over the river bend, great for kids and dogs.", source: "camper forums / Komoot", stopLength: "short" },
  { name: "Spitz an der Donau (Tausendeimerberg)", type: "town", lat: 48.3644, lng: 15.4147, near: "Wachau / Melk", blurb: "Quintessential Wachau wine village around the terraced 'Thousand-Bucket Hill', with apricot stalls and a fun car ferry across the Danube.", source: "campercontact / Tripadvisor", stopLength: "short" },
  { name: "Royal Palace of Gödöllő (Grassalkovich)", type: "castle", lat: 47.5969, lng: 19.3597, near: "Hungaroring / Mogyoród", blurb: "Empress Sisi's favourite baroque palace with lavish rooms and shaded gardens, an easy cultural break fifteen minutes from the Hungaroring.", source: "Tripadvisor top things to do", stopLength: "half-day" },
  { name: "Fisherman's Bastion", type: "viewpoint", lat: 47.502, lng: 19.0348, near: "Budapest", blurb: "Fairytale white turrets on Castle Hill framing the best panorama of Parliament and the Danube, free to wander the lower terraces.", source: "Instagram-famous / Tripadvisor", stopLength: "short" },
  { name: "Széchenyi Thermal Bath", type: "attraction", lat: 47.5188, lng: 19.0819, near: "Budapest", blurb: "Europe's grand neo-baroque bathhouse with steaming outdoor pools, a memorable way to cool off after the race weekend.", source: "Instagram-famous / Tripadvisor", stopLength: "half-day" },
  { name: "Stift Klosterneuburg", type: "castle", lat: 48.3055, lng: 16.3256, near: "Klosterneuburg / Vienna", blurb: "Vast 900-year-old Augustinian abbey over the Danube with Austria's oldest winery and a shaded café, an easy first stop leaving Vienna.", source: "Tripadvisor / vienna.info", stopLength: "half-day" },
  { name: "Rossatzbach Danube beach", type: "lake", lat: 48.3921, lng: 15.5183, near: "Rossatz / Dürnstein, Wachau", blurb: "Quiet river beach with the classic framed view back to Dürnstein, a favourite camper spot for a dog-friendly summer swim.", source: "park4night / campercontact", stopLength: "short" },
  { name: "Kloster Weltenburg biergarten & Danube Gorge", type: "restaurant", lat: 48.8981, lng: 11.8214, near: "Kelheim (30 min south of Regensburg)", blurb: "Riverside Benedictine abbey with the world's oldest monastic brewery, serving dark Dunkel and pretzels in a shady beer garden by the Danube gorge.", source: "camper forums / bavaria.travel", stopLength: "half-day" },
  { name: "Walhalla Temple, Donaustauf", type: "viewpoint", lat: 49.0314, lng: 12.2285, near: "Donaustauf (20 min east of Regensburg)", blurb: "A colossal Parthenon-style marble temple on a hill with sweeping views over the Danube, worth the 358-step climb.", source: "Tripadvisor / Instagram", stopLength: "short" },
  { name: "Steinerne Brücke & Regensburg Old Town", type: "town", lat: 49.0206, lng: 12.0985, near: "Regensburg", blurb: "UNESCO medieval old town anchored by a 12th-century stone bridge over the Danube, with riverside biergartens by perimeter camper parking.", source: "Tripadvisor / camper forums", stopLength: "half-day" },
  { name: "Historische Wurstkuchl", type: "restaurant", lat: 49.0197, lng: 12.0994, near: "Regensburg (Danube riverside)", blurb: "Reputedly the world's oldest sausage kitchen, grilling charcoal bratwurst with sauerkraut by the stone bridge since the 12th century.", source: "Tripadvisor top things to do", stopLength: "short" },
  { name: "Plönlein, Rothenburg ob der Tauber", type: "attraction", lat: 49.3736, lng: 10.182, near: "Rothenburg ob der Tauber", blurb: "Rothenburg's most photographed corner, a forked lane with a leaning yellow timbered house that inspired Disney's Pinocchio.", source: "Instagram-famous / rothenburg.de", stopLength: "short" },
  { name: "Kaiserburg Nürnberg (Imperial Castle)", type: "castle", lat: 49.4577, lng: 11.0765, near: "Nuremberg old town", blurb: "Medieval imperial castle crowning the old town, with free-to-enter grounds giving a rooftop panorama over Nuremberg.", source: "Tripadvisor / bavaria.travel", stopLength: "half-day" },
  { name: "Henkersteg (Hangman's Bridge), Nuremberg", type: "attraction", lat: 49.453, lng: 11.074, near: "Nuremberg old town", blurb: "Covered wooden footbridge and half-timbered hangman's tower over the Pegnitz, one of the city's most photogenic riverside spots.", source: "Instagram-famous / Creative Travel Guide", stopLength: "photo" },
  { name: "Reichsburg Cochem", type: "castle", lat: 50.1454, lng: 7.1636, near: "Cochem / Mosel", blurb: "Fairytale hilltop castle above the Mosel with sweeping vineyard-and-river views, a classic half-day tour or quick photo from the far bank.", source: "Tripadvisor / Instagram", stopLength: "half-day" },
  { name: "Burg Eltz", type: "castle", lat: 50.2058, lng: 7.3369, near: "Cochem / Mosel", blurb: "Germany's most photographed medieval castle, tucked in a wooded valley and reached by a scenic downhill walk from the Wierschem car park.", source: "park4night / Tripadvisor", stopLength: "half-day" },
  { name: "Alte Thorschenke, Cochem", type: "restaurant", lat: 50.1466, lng: 7.1683, near: "Cochem / Mosel", blurb: "One of Germany's oldest inns (1332), a half-timbered landmark serving Mosel wine and regional food in Cochem's old town.", source: "Tripadvisor / Instagram", stopLength: "short" },
  { name: "Beilstein old town", type: "town", lat: 50.1019, lng: 7.2372, near: "Cochem / Mosel", blurb: "Tiny 'Sleeping Beauty' Mosel village of cobbled lanes below a ruined castle, a lovely short wander and riverside photo stop.", source: "camper forums / Tripadvisor", stopLength: "short" },
  { name: "Marksburg, Braubach", type: "castle", lat: 50.2761, lng: 7.6497, near: "Koblenz", blurb: "The only Rhine hilltop castle never destroyed, above Braubach, with guided tours and panoramic Rhine Gorge views.", source: "Tripadvisor top things to do", stopLength: "half-day" },
  { name: "Loreley Rock plateau", type: "viewpoint", lat: 50.1387, lng: 7.7295, near: "Koblenz", blurb: "Legendary 132 m slate cliff at the Rhine's narrowest bend, with a plateau viewpoint and dramatic gorge photos.", source: "Tripadvisor / Instagram", stopLength: "short" },
  { name: "Deutsches Eck, Koblenz", type: "attraction", lat: 50.3641, lng: 7.6058, near: "Koblenz", blurb: "The dramatic headland where the Mosel meets the Rhine, with a giant Kaiser Wilhelm monument and a cable car up to Ehrenbreitstein Fortress.", source: "Tripadvisor top things to do", stopLength: "short" },
  { name: "Citadelle de Dinant", type: "castle", lat: 50.2597, lng: 4.9126, near: "Belgian Ardennes", blurb: "Cliff-top citadel over the Meuse above a candy-coloured bulb-domed church, reached by cable car or 400 steps for an iconic Ardennes photo.", source: "Tripadvisor / Instagram", stopLength: "half-day" },
  { name: "Durbuy", type: "town", lat: 50.3532, lng: 5.4561, near: "Belgian Ardennes", blurb: "Billed as the 'smallest town in the world', a pretty cluster of stone lanes on the Ourthe and a favourite dog-friendly camper detour.", source: "camper forums / Tripadvisor", stopLength: "short" },
];
